// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineJudge.Infrastructure.Persistence;

#nullable disable

namespace OnlineJudge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OnlineJudgeDbContext))]
    [Migration("20260828133844_AddLeaderboardSeasons")]
    partial class AddLeaderboardSeasons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnlineJudge.Domain.Entities.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Challenges", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ChallengeParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ChallengeId", "UserId")
                        .IsUnique();

                    b.ToTable("ChallengeParticipants", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ChallengeTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlgorithmProblemId")
                        .HasColumnType("uuid");

                    b.Property<int>("BoardX")
                        .HasColumnType("integer");

                    b.Property<int>("BoardY")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmProblemId");

                    b.HasIndex("ChallengeId", "BoardX", "BoardY")
                        .IsUnique();

                    b.ToTable("ChallengeTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChallengeTasks_BoardX", "\"BoardX\" >= 0 AND \"BoardX\" <= 7");

                            t.HasCheckConstraint("CK_ChallengeTasks_BoardY", "\"BoardY\" >= 0 AND \"BoardY\" <= 7");
                        });
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ChallengeTaskAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("ChallengeTaskId");

                    b.HasIndex("UserId", "ChallengeTaskId")
                        .IsUnique();

                    b.ToTable("ChallengeTaskAnswers", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ChallengeTaskCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("ChallengeTaskId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("UserId", "ChallengeTaskId")
                        .IsUnique();

                    b.ToTable("ChallengeTaskCompletions", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ChallengeTaskFileSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ReviewScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("ChallengeTaskId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("UserId", "ChallengeTaskId")
                        .IsUnique();

                    b.ToTable("ChallengeTaskFileSubmissions", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FreezeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("PublicUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsCurrent")
                        .IsUnique()
                        .HasFilter("\"IsCurrent\" = TRUE");

                    b.ToTable("LeaderboardSeasons", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaderboardSeasons_TimeOrder", "\"StartAt\" < \"FreezeAt\" AND \"FreezeAt\" < \"PublicUntil\"");
                        });
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeasonAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SeasonId", "Alias")
                        .IsUnique();

                    b.HasIndex("SeasonId", "UserId")
                        .IsUnique();

                    b.ToTable("LeaderboardSeasonAliases", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeasonArchiveEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FinalBaseScore")
                        .HasColumnType("integer");

                    b.Property<int>("FinalRank")
                        .HasColumnType("integer");

                    b.Property<int>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastScoreImprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<int>("SolvedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasAnonymous")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SeasonId", "FinalRank")
                        .IsUnique();

                    b.HasIndex("SeasonId", "UserId")
                        .IsUnique();

                    b.ToTable("LeaderboardSeasonArchiveEntries", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeasonArchiveProblemScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArchiveEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("BaseScore")
                        .HasColumnType("integer");

                    b.Property<int>("EarnedBaseScore")
                        .HasColumnType("integer");

                    b.Property<int>("FinalProblemScore")
                        .HasColumnType("integer");

                    b.Property<int>("MemoryBonus")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProblemTitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RuntimeBonus")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeBonus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("ArchiveEntryId", "ProblemId")
                        .IsUnique();

                    b.ToTable("LeaderboardSeasonArchiveProblemScores", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeasonProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.HasIndex("SeasonId", "ProblemId")
                        .IsUnique();

                    b.ToTable("LeaderboardSeasonProblems", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaderboardSeasonProblems_BaseScore", "\"BaseScore\" >= 0");
                        });
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardUserProblemScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BestBaseScore")
                        .HasColumnType("integer");

                    b.Property<int?>("BestMemoryKb")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BestPerformanceSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BestRuntimeMs")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FirstFullScoreAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFullScore")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastScoreImprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonProblemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BestPerformanceSubmissionId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.HasIndex("SeasonProblemId", "UserId")
                        .IsUnique();

                    b.HasIndex("SeasonId", "ProblemId", "UserId")
                        .IsUnique();

                    b.ToTable("LeaderboardUserProblemScores", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaderboardUserProblemScores_BaseScore", "\"BestBaseScore\" >= 0");
                        });
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllowedLanguagesMask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FunctionSpecJson")
                        .HasColumnType("text");

                    b.Property<string>("InputDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("JudgeMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("MemoryLimitMb")
                        .HasColumnType("integer");

                    b.Property<string>("OutputDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StarterCodeJson")
                        .HasColumnType("text");

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Problems", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ProblemCollaborator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanEditProblem")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageTestCases")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("ProblemId", "UserId")
                        .IsUnique();

                    b.ToTable("ProblemCollaborators", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ProblemJudgeAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StorageRelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.HasIndex("ProblemId", "Language", "NormalizedFileName")
                        .IsUnique();

                    b.ToTable("ProblemJudgeAssets", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.SiteSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SiteSettings", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChallengeTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<int?>("MemoryUsedKb")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeUsedMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeTaskId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.SubmissionCaseResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualOutput")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedJsonSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedOutputSnapshot")
                        .HasColumnType("text");

                    b.Property<int?>("MemoryUsedKb")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreSnapshot")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TimeUsedMs")
                        .HasColumnType("integer");

                    b.Property<int?>("VisibilitySnapshot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("TestCaseId");

                    b.ToTable("SubmissionCaseResults", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.TeamInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("TeamId", "InvitedUserId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("TeamInvitations", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = TRUE");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = TRUE");

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.TeamProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("LastSyncAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LastSyncStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NormalizedRepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TeamId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TeamId", "NormalizedRepositoryUrl")
                        .IsUnique();

                    b.ToTable("TeamProjects", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedJson")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.ToTable("TestCases", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsBlacklisted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLeaderboardAnonymous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("\"PhoneNumber\" IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.UserAppearanceSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BackgroundEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("BackgroundImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal>("OverlayOpacity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(0.65m);

                    b.Property<decimal>("PositionX")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(50m);

                    b.Property<decimal>("PositionY")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(50m);

                    b.Property<decimal>("Scale")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(1m);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserAppearanceSettings", (string)null);
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.Challenge", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedChallenges")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ChallengeParticipant", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Participants")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.User", "User")
                        .WithMany("ChallengeParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ChallengeTask", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.Problem", "AlgorithmProblem")
                        .WithMany("ChallengeTasks")
                        .HasForeignKey("AlgorithmProblemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnlineJudge.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Tasks")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlgorithmProblem");

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ChallengeTaskAnswer", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Answers")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.ChallengeTask", "ChallengeTask")
                        .WithMany("Answers")
                        .HasForeignKey("ChallengeTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("ChallengeTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ChallengeTaskCompletion", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Completions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.ChallengeTask", "ChallengeTask")
                        .WithMany("Completions")
                        .HasForeignKey("ChallengeTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OnlineJudge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("ChallengeTask");

                    b.Navigation("Submission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ChallengeTaskFileSubmission", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.Challenge", "Challenge")
                        .WithMany("FileSubmissions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.ChallengeTask", "ChallengeTask")
                        .WithMany("FileSubmissions")
                        .HasForeignKey("ChallengeTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnlineJudge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("ChallengeTask");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeason", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeasonAlias", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.LeaderboardSeason", "Season")
                        .WithMany("Aliases")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeasonArchiveEntry", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.LeaderboardSeason", "Season")
                        .WithMany("ArchiveEntries")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeasonArchiveProblemScore", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.LeaderboardSeasonArchiveEntry", "ArchiveEntry")
                        .WithMany("ProblemScores")
                        .HasForeignKey("ArchiveEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.LeaderboardSeason", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveEntry");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeasonProblem", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.LeaderboardSeason", "Season")
                        .WithMany("Problems")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardUserProblemScore", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.Submission", "BestPerformanceSubmission")
                        .WithMany()
                        .HasForeignKey("BestPerformanceSubmissionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OnlineJudge.Domain.Entities.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.LeaderboardSeason", "Season")
                        .WithMany("UserProblemScores")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.LeaderboardSeasonProblem", "SeasonProblem")
                        .WithMany("UserScores")
                        .HasForeignKey("SeasonProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BestPerformanceSubmission");

                    b.Navigation("Problem");

                    b.Navigation("Season");

                    b.Navigation("SeasonProblem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ProblemCollaborator", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.User", "GrantedByUser")
                        .WithMany("GrantedProblemCollaborations")
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.Problem", "Problem")
                        .WithMany("Collaborators")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.User", "User")
                        .WithMany("ProblemCollaborations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrantedByUser");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ProblemJudgeAsset", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.Problem", "Problem")
                        .WithMany("JudgeAssets")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.Submission", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.ChallengeTask", "ChallengeTask")
                        .WithMany()
                        .HasForeignKey("ChallengeTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OnlineJudge.Domain.Entities.Problem", "Problem")
                        .WithMany("Submissions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChallengeTask");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.SubmissionCaseResult", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.Submission", "Submission")
                        .WithMany("CaseResults")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.TestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.Team", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.User", "OwnerUser")
                        .WithMany("OwnedTeams")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.TeamInvitation", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.User", "InvitedByUser")
                        .WithMany("SentTeamInvitations")
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.User", "InvitedUser")
                        .WithMany("TeamInvitations")
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.Team", "Team")
                        .WithMany("Invitations")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("InvitedUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.User", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.TeamProject", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTeamProjects")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineJudge.Domain.Entities.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.Problem", "Problem")
                        .WithMany("TestCases")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.UserAppearanceSetting", b =>
                {
                    b.HasOne("OnlineJudge.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("OnlineJudge.Domain.Entities.UserAppearanceSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.Challenge", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Completions");

                    b.Navigation("FileSubmissions");

                    b.Navigation("Participants");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.ChallengeTask", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Completions");

                    b.Navigation("FileSubmissions");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeason", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("ArchiveEntries");

                    b.Navigation("Problems");

                    b.Navigation("UserProblemScores");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeasonArchiveEntry", b =>
                {
                    b.Navigation("ProblemScores");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.LeaderboardSeasonProblem", b =>
                {
                    b.Navigation("UserScores");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.Problem", b =>
                {
                    b.Navigation("ChallengeTasks");

                    b.Navigation("Collaborators");

                    b.Navigation("JudgeAssets");

                    b.Navigation("Submissions");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.Submission", b =>
                {
                    b.Navigation("CaseResults");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.Team", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Members");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("OnlineJudge.Domain.Entities.User", b =>
                {
                    b.Navigation("ChallengeParticipants");

                    b.Navigation("CreatedChallenges");

                    b.Navigation("CreatedTeamProjects");

                    b.Navigation("GrantedProblemCollaborations");

                    b.Navigation("OwnedTeams");

                    b.Navigation("ProblemCollaborations");

                    b.Navigation("SentTeamInvitations");

                    b.Navigation("Submissions");

                    b.Navigation("TeamInvitations");

                    b.Navigation("TeamMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
